import { getPosts, getPostBySlug, extractHeadings, getPostListDescription } from "@/lib/content";
import { MDXRemote } from "next-mdx-remote/rsc";
import remarkGfm from "remark-gfm";
import remarkWikiLink from "remark-wiki-link";
import rehypeSlug from "rehype-slug";
import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Bookmark, BookmarkCheck, CalendarDays, CheckCircle2, Clock3 } from "lucide-react";
import type { ComponentPropsWithoutRef } from "react";
import type { Metadata } from "next";
import { Breadcrumbs } from "@/components/layout/Breadcrumbs";
import TocSidebar from "@/components/layout/TocSidebar";
import Lightbox from "@/components/layout/Lightbox";
import { Reveal } from "@/components/layout/Reveal";
import ReadingProgress from "@/components/article/ReadingProgress";
import { CopyCodeButton } from "@/components/article/CopyCodeButton";
import { getCurrentUser } from "@/lib/member-auth";
import { canReadPost, getPostAccessLabel } from "@/lib/post-access";
import { getMemberPostActivityState, recordPostRead } from "@/lib/member-post-activity";
import { logMemberAccess } from "@/lib/member-access-log";
import { createContentWatermark, injectWatermarkIntoMarkdown, needsContentProtection } from "@/lib/watermark";
import { toggleBookmark, toggleReadLater } from "./actions";
import ContentProtection from "@/components/article/ContentProtection";
import "./article.css";

const SITE_URL = "https://blog.sovoice.asia";
const SITE_NAME = "E-Life";

export const dynamic = "force-dynamic";
export const fetchCache = "force-no-store";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const post = getPostBySlug(decodeURIComponent(slug));

  if (!post) {
    return { title: "Not Found" };
  }

  const { title, description, date, tags, cover } = post.meta;
  const safeDescription = getPostListDescription(post);
  const ogDescription = safeDescription || `${title} — E-Life 博客`;
  const ogImage = cover
    ? cover.startsWith("http")
      ? cover
      : `${SITE_URL}${cover}`
    : `${SITE_URL}/images/og-default.png`;

  return {
    title,
    description: ogDescription,
    openGraph: {
      title,
      description: ogDescription,
      type: "article",
      publishedTime: date,
      url: `${SITE_URL}/articles/${post.slug}`,
      siteName: SITE_NAME,
      locale: "zh_CN",
      images: [
        {
          url: ogImage,
          width: 1792,
          height: 1024,
          alt: title,
        },
      ],
      tags,
    },
    twitter: {
      card: "summary_large_image",
      title,
      description: ogDescription,
      images: [ogImage],
    },
  };
}

export default async function PostPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const post = getPostBySlug(decodeURIComponent(slug));

  if (!post) {
    notFound();
  }

  const user = await getCurrentUser();
  const access = post.meta.access ?? "public";
  const canRead = canReadPost(user, access);
  const accessLabel = getPostAccessLabel(access);
  const activityState = user ? await getMemberPostActivityState(user.id, post.slug) : { bookmarked: false, readLater: false };
  if (user && canRead) {
    await recordPostRead(user.id, post.slug);
  }

  // Extract headings for TOC (with IDs generated by github-slugger, matching rehype-slug)
  const tocHeadings = canRead ? extractHeadings(post.content) : [];
  const shouldProtectContent = canRead && user && needsContentProtection(access);
  const contentWatermark = shouldProtectContent ? createContentWatermark({ userId: user.id, slug: post.slug }) : null;
  if (user && contentWatermark) {
    await logMemberAccess({ action: "view_post", userId: user.id, targetId: `${post.slug}:${contentWatermark.digest}` });
  }
  const protectedContent = contentWatermark
    ? injectWatermarkIntoMarkdown(post.content, contentWatermark.text)
    : post.content;

  // 预计阅读时长:中文约 400 字/分钟
  const readMinutes = Math.max(1, Math.round(post.content.replace(/\s+/g, "").length / 400));

  // 相邻文章导航(getPosts 按日期倒序:索引小 = 较新)
  const posts = getPosts();
  const postIndex = posts.findIndex((p) => p.slug === post.slug);
  const newerPost = postIndex > 0 ? posts[postIndex - 1] : null;
  const olderPost = postIndex !== -1 && postIndex < posts.length - 1 ? posts[postIndex + 1] : null;

  // Define custom MDX components (like styling standard Markdown elements with Tailwind)
  const components = {
    h1: (props: ComponentPropsWithoutRef<"h1">) => <h1 className="mb-4 mt-10 text-3xl font-black tracking-normal text-[color:var(--foreground)]" {...props} />,
    h2: (props: ComponentPropsWithoutRef<"h2">) => <h2 className="mb-4 mt-10 border-b-2 border-[color:var(--line)] pb-3 text-2xl font-black tracking-normal text-[color:var(--foreground)]" {...props} />,
    h3: (props: ComponentPropsWithoutRef<"h3">) => <h3 className="mb-3 mt-8 text-xl font-black tracking-normal text-[color:var(--foreground)]" {...props} />,
    p: (props: ComponentPropsWithoutRef<"p">) => <p className="leading-8 text-[color:color-mix(in_srgb,var(--foreground)_84%,var(--walnut))] [&:not(:first-child)]:mt-6" {...props} />,
    ul: (props: ComponentPropsWithoutRef<"ul">) => <ul className="my-6 ml-6 list-disc text-[color:color-mix(in_srgb,var(--foreground)_84%,var(--walnut))] [&>li]:mt-2" {...props} />,
    ol: (props: ComponentPropsWithoutRef<"ol">) => <ol className="my-6 ml-6 list-decimal text-[color:color-mix(in_srgb,var(--foreground)_84%,var(--walnut))] [&>li]:mt-2" {...props} />,
    li: (props: ComponentPropsWithoutRef<"li">) => <li className="leading-7" {...props} />,
    a: (props: ComponentPropsWithoutRef<"a">) => {
      const { href = "", ...rest } = props;
      // Handle internal wiki links
      if (href.startsWith('/')) {
        return <Link href={href} className="font-black text-[color:var(--accent-strong)] hover:underline" {...rest} />;
      }
      return <a href={href} className="font-black text-[color:var(--accent-strong)] hover:underline" target="_blank" rel="noopener noreferrer" {...rest} />;
    },
    blockquote: (props: ComponentPropsWithoutRef<"blockquote">) => <blockquote className="mt-6 border-l-[6px] border-[color:var(--mustard)] bg-[color:var(--surface)] py-3 pl-6 font-bold text-[color:var(--walnut)] shadow-[3px_3px_0_var(--ink)]" {...props} />,
    code: (props: ComponentPropsWithoutRef<"code">) => <code className="relative rounded-[2px] border border-[color:var(--line)] bg-[color:rgb(212_165_116_/_28%)] px-[0.35rem] py-[0.2rem] font-mono text-sm text-[color:var(--foreground)]" {...props} />,
    pre: (props: ComponentPropsWithoutRef<"pre">) => (
      <div className="code-block-wrapper">
        <CopyCodeButton />
        <pre className="pre-dark" {...props} />
      </div>
    ),
    // Handle images specifically to make them responsive
    img: (props: ComponentPropsWithoutRef<"img">) => <img className="mx-auto my-8 max-h-[600px] rounded-[2px] border-2 border-[color:var(--line)] object-contain shadow-[var(--shadow-small)]" alt={props.alt || ''} {...props} />
  };

  return (
    <>
      {canRead && <ReadingProgress targetId="post-body" />}
      <div className="mx-auto flex w-full max-w-[90rem] items-start gap-8 px-3 pb-8 sm:px-4 xl:px-6">
        <TocSidebar headings={tocHeadings} />
        <article className="mx-auto min-w-0 max-w-4xl flex-1">
          <Breadcrumbs
            items={[
              { label: "首页", href: "/" },
              { label: "写作", href: "/writing" },
              { label: "文章", href: "/articles" },
              { label: post.meta.title },
            ]}
          />

          <Link href="/articles" className="mb-8 inline-flex items-center gap-2 text-sm font-black text-[color:var(--walnut)] transition-colors hover:text-[color:var(--accent-strong)]">
            <ArrowLeft className="h-4 w-4" />
            返回文章列表
          </Link>

          <header className="mcm-panel mb-12 space-y-5 overflow-hidden p-0 md:p-0">
            {post.meta.cover && (
              <div className="relative aspect-[21/9] overflow-hidden border-b-2 border-[color:var(--line)] bg-[color:var(--paper-deep)]">
                <img
                  src={post.meta.cover}
                  alt=""
                  className="h-full w-full object-cover"
                />
              </div>
            )}
            <div className="space-y-5 p-7 md:p-10">
            <p className="section-kicker">Post</p>
            <h1 className="press-title text-4xl font-black leading-tight tracking-normal text-[color:var(--foreground)] md:text-6xl">
              {post.meta.title}
            </h1>

            <div className="flex flex-wrap items-center gap-x-4 gap-y-2 text-sm font-bold text-[color:var(--walnut)]">
              <time dateTime={post.meta.date} className="inline-flex items-center gap-1.5">
                <CalendarDays className="h-4 w-4" aria-hidden="true" />
                发布于 {new Date(post.meta.date).toLocaleDateString('zh-CN', {
                  year: 'numeric',
                  month: 'long',
                  day: 'numeric'
                })}
              </time>

              <span className="inline-flex items-center gap-1.5">
                <Clock3 className="h-4 w-4" aria-hidden="true" />
                约 {readMinutes} 分钟读完
              </span>

              {access !== "public" && (
                <span className="mcm-tag">{accessLabel}</span>
              )}
            </div>

            {post.meta.tags && post.meta.tags.length > 0 && (
              <div className="flex flex-wrap items-center gap-2">
                {post.meta.tags.map((tag) => (
                  <Link key={tag} href={`/tags/${tag}`} className="mcm-tag">
                    #{tag}
                  </Link>
                ))}
              </div>
            )}

            <div className="flex flex-wrap items-center gap-3">
              <form action={toggleBookmark}>
                <input type="hidden" name="slug" value={post.slug} />
                <input type="hidden" name="enabled" value={activityState.bookmarked ? "false" : "true"} />
                <button
                  type="submit"
                  aria-pressed={activityState.bookmarked}
                  className={activityState.bookmarked ? "mcm-button mcm-button-primary" : "mcm-button mcm-button-secondary"}
                  style={activityState.bookmarked ? { transform: "translate(2px, 2px)", boxShadow: "1px 1px 0 var(--ink)" } : undefined}
                >
                  {activityState.bookmarked ? <BookmarkCheck className="h-4 w-4" aria-hidden="true" /> : <Bookmark className="h-4 w-4" aria-hidden="true" />}
                  {activityState.bookmarked ? "已收藏" : "收藏文章"}
                </button>
              </form>
              <form action={toggleReadLater}>
                <input type="hidden" name="slug" value={post.slug} />
                <input type="hidden" name="enabled" value={activityState.readLater ? "false" : "true"} />
                <button
                  type="submit"
                  aria-pressed={activityState.readLater}
                  className={activityState.readLater ? "mcm-button mcm-button-primary" : "mcm-button mcm-button-secondary"}
                  style={activityState.readLater ? { transform: "translate(2px, 2px)", boxShadow: "1px 1px 0 var(--ink)" } : undefined}
                >
                  {activityState.readLater ? <CheckCircle2 className="h-4 w-4" aria-hidden="true" /> : <Clock3 className="h-4 w-4" aria-hidden="true" />}
                  {activityState.readLater ? "已加入稍后读" : "稍后阅读"}
                </button>
              </form>
              {!user && (
                <p className="self-center text-sm font-bold text-[color:var(--walnut)]">登录后可保存阅读偏好。</p>
              )}
            </div>
            </div>
          </header>

          <div id="post-body" className="post-body mx-auto">
            {canRead ? (
              <ContentProtection protectedContent={Boolean(shouldProtectContent)}>
              <Lightbox>
                <MDXRemote
                  source={protectedContent}
                  components={components}
                  options={{
                    mdxOptions: {
                      remarkPlugins: [
                        remarkGfm,
                        [remarkWikiLink, {
                          // Setup to resolve Obsidian's [[Links]]
                          hrefTemplate: (permalink: string) => `/articles/${permalink}`
                        }]
                      ],
                      rehypePlugins: [rehypeSlug],
                    }
                  }}
                />
              </Lightbox>
              </ContentProtection>
            ) : (
              <section className="mcm-panel space-y-5 p-7 md:p-10">
                <p className="section-kicker">Member Only</p>
                <h2 className="text-3xl font-black text-[color:var(--foreground)]">
                  这篇文章需要 {accessLabel} 解锁
                </h2>
                <p className="font-bold leading-8 text-[color:var(--walnut)]">
                  公开文章仍然可以直接阅读。分级文章会保留标题、摘要和标签，正文只对对应等级会员开放。
                </p>
                <div className="flex flex-wrap gap-3">
                  <Link href={`/login?next=${encodeURIComponent(`/articles/${post.slug}`)}`} className="mcm-button">
                    登录会员账号
                  </Link>
                  <Link href="/subscribe" className="mcm-button-secondary">
                    查看会员等级
                  </Link>
                </div>
              </section>
            )}
          </div>

          <Reveal className="mt-14">
            <footer className="space-y-6">
              {(newerPost || olderPost) && (
                <nav aria-label="相邻文章" className="grid gap-4 sm:grid-cols-2">
                  {newerPost && (
                    <Link
                      href={`/articles/${newerPost.slug}`}
                      className="mcm-card group flex min-h-[6.5rem] flex-col justify-between gap-3 p-5"
                    >
                      <span className="mono-label inline-flex items-center gap-1.5 text-xs font-extrabold uppercase text-[color:var(--walnut)]">
                        <ArrowLeft className="h-3.5 w-3.5 transition-transform duration-150 group-hover:-translate-x-0.5" aria-hidden="true" />
                        上一篇 · Newer
                      </span>
                      <span className="line-clamp-2 text-lg font-black leading-snug text-[color:var(--foreground)] transition-colors duration-150 group-hover:text-[color:var(--accent-strong)]">
                        {newerPost.meta.title}
                      </span>
                    </Link>
                  )}
                  {olderPost && (
                    <Link
                      href={`/articles/${olderPost.slug}`}
                      className="mcm-card group flex min-h-[6.5rem] flex-col items-end justify-between gap-3 p-5 text-right sm:col-start-2"
                    >
                      <span className="mono-label inline-flex items-center gap-1.5 text-xs font-extrabold uppercase text-[color:var(--walnut)]">
                        下一篇 · Older
                        <ArrowRight className="h-3.5 w-3.5 transition-transform duration-150 group-hover:translate-x-0.5" aria-hidden="true" />
                      </span>
                      <span className="line-clamp-2 text-lg font-black leading-snug text-[color:var(--foreground)] transition-colors duration-150 group-hover:text-[color:var(--accent-strong)]">
                        {olderPost.meta.title}
                      </span>
                    </Link>
                  )}
                </nav>
              )}

              <div className="flex justify-center">
                <Link href="/articles" className="mcm-button mcm-button-secondary">
                  <ArrowLeft className="h-4 w-4" aria-hidden="true" />
                  返回文章列表
                </Link>
              </div>
            </footer>
          </Reveal>
        </article>
      </div>
    </>
  );
}
